### ISSUE TITLE
php-fpm-5.6.40-29.el7.remi.x86_64 no longer writing to error log

### ISSUE THREAD

**Issue by aran112000** [remicollet/remirepo#183] opened 2021-08-31 14:35 UTC
Since updating to php-fpm-5.6.40-29.el7.remi.x86_64 over night, PHP errors are no longer respecting the following directive within our www.conf pool:

`php_admin_value[error_log] = /path/to/file.log`

We've run this update on several servers and can recreate the error logging stopping after this package update running on Centos 7.9.2009.

**Comment by remicollet** [comment] 2021-09-01 05:45
Sorry, but cannot reproduce
Default value 
```
php_admin_value[error_log] = /var/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on
```
is properly honored

**Comment by remicollet** [comment] 2021-09-01 06:05
Confirmed on a fresh install, everything works as expected

```
# rpm -q php-fpm
php-fpm-5.6.40-29.el7.remi.x86_64

# cat /var/log/php-fpm/www-error.log
[01-Sep-2021 08:02:52 Europe/Paris] Debug from: /var/www/html/info.php
```

Check directory permissions and SElinux context

**Comment by aran112000** [comment] 2021-09-01 14:16
Thanks for looking at this so quickly @remicollet

We were previously running `php-fpm-5.6.40-28.el7.remi.x86_64`, so only a minor bump and we couldn't see anything in the changelog that would explain the issue either.

No permissions changes, still running as the same user/group within FPM and on the directory and we don't have SELinux enforced on this instance presently whilst testing.

**Comment by remicollet** [comment] 2021-11-20 14:46
cannot reproduce, no new info, and no other report from other users, so closing

**Closed by remicollet** 2021-11-20 14:46 UTC
