### ISSUE TITLE
Modify Remi Wizard to clarify switch-to command is only needed on systems that already have a different remi php version module set.

### ISSUE THREAD

**Issue by awkohr** [remicollet/remirepo#274] opened 2024-10-28 19:52 UTC
The current wording of the Remi PHP wizard is currently worded that it may lead users that are doing a new install to try to do steps that appear to only be required when upgrading from an older version to a newer version, as the switch-to php.... step does not appear to not be needed for a clean install.  The current wording makes it seem like it is needed regardless. 

Steps to reproduce:
1. Build a new RHEL 9 systems 
2. Start the remi wizard 
3. Choosing Operating systems RHEL 9.4, wanted PHP 8.2.25..., Type of installation: Default/Single version .... Architecture x86_64. 

Actual Results:
...
 "PHP version 8.2 packages are available for RHEL 9 in remi-modular repository

You have to enable the module stream for 8.2, and update the old version if installed:
    dnf module switch-to php:remi-8.2

If no version is installed, command to install the php stream default profile:
    dnf module install php:remi-8.2"
...
Expected Results:
... 
 "PHP version 8.2 packages are available for RHEL 9 in remi-modular repository

If you are upgrading from a previous version, You have to enable the module stream for 8.2, and update the old version.
    dnf module switch-to php:remi-8.2

If no version is installed, command to install the php stream default profile:
    dnf module install php:remi-8.2"
...

Possible solutions: 
A. Updated the wording to put the if you are upgarding at the start of the line, similar to what is in the expected results. 
or
B. Ask a question of whether this is being installed on a system without php already installed and then not include any switch-to line if it is a clean install and if it is an upgrade include "Enable the module stream for 8.2, and update the old version dnf module switch-to php:remi-8.2"

Additional Notes:
Not sure if the switch-to line would just have worked had it had a module profile profile defined like php:remi-8.2/minimal. However I was able to install remi PHP without the change-to line on a new RHEL 9 system.

**Comment by remicollet** [comment] 2024-10-29 06:42
The problem is that there is more than 2 cases

- a stream version can be enable or not
- some packages may be installed of not

As explained by the wizard

```
You have to enable the module stream for 8.2, and update the old version if installed:
dnf module switch-to php:remi-8.2
```

So the switch-to is useful to ensure no other stream is enabled, even if no package installed
Without the switch-to, the install may fail
Without the switch-to, a module reset is required

So IMHO, current wizard instructions are OK.

**Comment by remicollet** [comment] 2024-10-29 06:51
To confirm, using this [Docker test image](https://git.remirepo.net/cgit/tools/docker.git/tree/ubi9-remi-php84.dockerfile)

```
...
Dependencies resolved.
================================================================================
 Package           Architecture     Version             Repository         Size
================================================================================
Enabling module streams:
 php                                remi-8.4                                   

Transaction Summary
================================================================================

Complete!
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:00:01 ago on Tue Oct 29 06:48:13 2024.
Dependencies resolved.
================================================================================
 Package           Arch    Version                  Repository             Size
================================================================================
Installing group/module packages:
 php-cli           x86_64  8.4.0~rc3-1.el9.remi     remi-modular          3.8 M
 php-common        x86_64  8.4.0~rc3-1.el9.remi     remi-modular          750 k
 php-fpm           x86_64  8.4.0~rc3-1.el9.remi     remi-modular          2.0 M
 php-mbstring      x86_64  8.4.0~rc3-1.el9.remi     remi-modular          537 k
 php-xml           x86_64  8.4.0~rc3-1.el9.remi     remi-modular          920 k
Installing dependencies:
 httpd-filesystem  noarch  2.4.57-11.el9_4.1        ubi-9-appstream-rpms   14 k
 libedit           x86_64  3.1-38.20210216cvs.el9   ubi-9-baseos-rpms     107 k
 libxslt           x86_64  1.1.34-9.el9             ubi-9-appstream-rpms  247 k
 oniguruma5php     x86_64  6.9.9-1.el9.remi         remi-safe             219 k
Installing weak dependencies:
 nginx-filesystem  noarch  1:1.20.1-16.el9_4.1      ubi-9-appstream-rpms   11 k
Installing module profiles:
 php/common                                                                    

Transaction Summary
================================================================================
Install  10 Packages

Total download size: 8.6 M
Installed size: 41 M
Downloading Packages:
(1/10): php-common-8.4.0~rc3-1.el9.remi.x86_64. 6.0 MB/s | 750 kB     00:00    
(2/10): php-fpm-8.4.0~rc3-1.el9.remi.x86_64.rpm  13 MB/s | 2.0 MB     00:00    
(3/10): php-mbstring-8.4.0~rc3-1.el9.remi.x86_6  13 MB/s | 537 kB     00:00    
(4/10): php-cli-8.4.0~rc3-1.el9.remi.x86_64.rpm  21 MB/s | 3.8 MB     00:00    
(5/10): oniguruma5php-6.9.9-1.el9.remi.x86_64.r 9.5 MB/s | 219 kB     00:00    
(6/10): php-xml-8.4.0~rc3-1.el9.remi.x86_64.rpm  28 MB/s | 920 kB     00:00    
(7/10): httpd-filesystem-2.4.57-11.el9_4.1.noar 187 kB/s |  14 kB     00:00    
(8/10): libedit-3.1-38.20210216cvs.el9.x86_64.r 1.1 MB/s | 107 kB     00:00    
(9/10): nginx-filesystem-1.20.1-16.el9_4.1.noar 636 kB/s |  11 kB     00:00    
(10/10): libxslt-1.1.34-9.el9.x86_64.rpm        2.1 MB/s | 247 kB     00:00    
--------------------------------------------------------------------------------
Total                                            23 MB/s | 8.6 MB     00:00     
Remi's Modular repository for Enterprise Linux  3.0 MB/s | 3.1 kB     00:00    
Importing GPG key 0x478F8947:
 Userid     : "Remi's RPM repository (https://rpms.remirepo.net/) <remi@remirepo.net>"
 Fingerprint: B1AB F71E 14C9 D748 97E1 98A8 B195 27F1 478F 8947
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el9
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
...
```

**Comment by awkohr** [comment] 2024-10-30 18:42
This came up due to my remi-modular repo clone not passing through the default profile information so, I may have started over analyzing things and started down the wrong route. Though without using the switch-to command on a fresh install it seems to have installed for me.  
 
As a little note, your initial responses command output was unclear as to exactly what you were trying to show, because you don't include the command you ran before the first set of triple dots.  It looks very different from what I was seeing on a clean system when I go to run "sudo dnf module switch-to php:remi-8.2" However, after a bit of testing I think you were showing the output of a command like "sudo dnf module switch-to php:remi-8.2" on a box that already had an another version installed on it, as when I first installed a  php:remi-8.1 module profile/packages and then ran a "sudo dnf module switch-to php:remi-8.2" I got similar output. 

I see your logic of that step should remain as someone could have the modules enabled but currently not have any packages installed.  However, it might be better for someone, like myself, that tends to over analyze instructions, (due to there being lots of wrong, outdated,...  documentation out there that ends up not working,) the current wording sounds like it might not need to be done/doesn't actually apply to new php installs and might be something that can be skipped. 

 It might be less questionable as to whether it should be skippable or worked through in the event of it not working the first time (as in my case due to cloned repo issues,) if you were to change "You have to enable the module stream for 8.2, and update the old version if installed:" to something like, "Enable the module stream for 8.2, and for those with php installed, agree to install the updated packages." It might be a bit clear.  I know its wording is similar but from my point of view it is a little clearer that the module switch-to command is really required for everybody, even if you aren't switching from a previous version.

Thank you for your time and consideration, and for confirming that it is really needed, as it helped to inform me that I needed to look for an underlying issue in our setup that was preventing this step from working that was making me think it was not needed for fresh installs.

**Comment by remicollet** [comment] 2024-10-31 03:09
> As a little note, your initial responses command output was unclear as to exactly what you were trying to show, because you don't include the command you ran before the first set of triple dots.

It is in the docker file.... `dnf -y module switch-to php:remi-8.4 && dnf -y module install   php:remi-8.4 `

**Comment by remicollet** [comment] 2024-10-31 08:09
Wizard answer a bit rewritten for clarity (and concise)

https://git.remirepo.net/cgit/web/rpms.git/commit/?id=c2143783f06f43cdb6b57aa6dd5c063dc01482af

**Comment by awkohr** [comment] 2024-10-31 11:31
Thank you.  I think your revised rewording takes away the chance of doubt.

**Comment by remicollet** [comment] 2024-10-31 13:32
Can we close this ticket ?

**Comment by awkohr** [comment] 2024-10-31 13:49
Sure.

**Closed** 2024-10-31 14:07 UTC
Labels: Discussion
