### ISSUE TITLE
ImageMagick6-1:6.9.12.16-1.el8.remi.x86_64 problem

### ISSUE THREAD

**Issue by it-can** [remicollet/remirepo#180] opened 2021-06-23 10:34 UTC
Issue is described here: https://github.com/Imagick/imagick/issues/441

**Comment by remicollet** [comment] 2021-06-23 10:43
So, looks like a regression in upstream IM 6.9.12-16...

Need a minimal reproducer (without laravel) reproducer to investigate.

Also ensure the webserver have been restarted after the update

**Comment by it-can** [comment] 2021-06-23 11:37
webserver is restarted and php-fpm also... I will try to create an example... But is happens on 1 system and the other not..

**Comment by it-can** [comment] 2021-06-23 13:06
I created a repo, https://github.com/it-can/imagick-bug

just clone it and run ```php index.php```

On my machine I got this error:

```
php index.php
free(): invalid next size (normal)
Afgebroken (geheugendump gemaakt)
```

**Comment by remicollet** [comment] 2021-06-23 13:06
@it-can did you mean that you install both php-pecl-imagick-**im7** with ImageMagicj7-libs (instead of php-pecl-imagick-**im6**)

**Comment by it-can** [comment] 2021-06-23 13:07
```
yum list installed | grep Image
ImageMagick6.x86_64                         1:6.9.12.15-1.el8.remi                  @remi
ImageMagick6-devel.x86_64                   1:6.9.12.15-1.el8.remi                  @remi
ImageMagick6-heic.x86_64                    1:6.9.12.15-1.el8.remi                  @remi-safe
ImageMagick6-libs.x86_64                    1:6.9.12.15-1.el8.remi                  @remi-safe
perl-Image-ExifTool.noarch                  12.16-3.el8                             @epel
```

**Comment by it-can** [comment] 2021-06-23 13:08
> @it-can did you mean that you install both php-pecl-imagick-**im7** with ImageMagicj7-libs (instead of php-pecl-imagick-**im6**)

I tried both versions, but got the same problem...

**Comment by remicollet** [comment] 2021-06-23 13:14
OK, can reproduce, definively not an bug in the package but a regression in upstream library

Please file a bug on 
* https://github.com/ImageMagick/ImageMagick
And
* https://github.com/ImageMagick/ImageMagick6/

**Comment by remicollet** [comment] 2021-06-23 13:20
From valgrind output

```
=480685== Invalid write of size 1
==480685==    at 0x4840643: memmove (vg_replace_strmem.c:1270)
==480685==    by 0xB3EEA6F6: UnknownInlinedFun (jpeg.c:2130)
==480685==    by 0xB3EEA6F6: WriteJPEGImage_ (jpeg.c:2813)
==480685==    by 0xB3EEBC98: WriteJPEGImage (jpeg.c:3032)
==480685==    by 0x11E99C1E: WriteImage (constitute.c:1286)
==480685==    by 0x11E68923: ImageToBlob (blob.c:2075)
==480685==    by 0x11C68471: zim_Imagick_getImagesBlob (in /usr/lib64/php/modules/imagick.so)
==480685==    by 0x55F6AC: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1730)
==480685==    by 0x55F6AC: execute_ex (zend_vm_execute.h:53901)
==480685==    by 0x56191A: zend_execute (zend_vm_execute.h:57993)
==480685==    by 0x4D845B: zend_execute_scripts (zend.c:1679)
==480685==    by 0x47571F: php_execute_script (main.c:2650)
==480685==    by 0x563A21: do_cli (php_cli.c:964)
==480685==    by 0x34444D: main (php_cli.c:1359)
==480685==  Address 0xb4122b90 is 0 bytes after a block of size 16,384 alloc'd
==480685==    at 0x483BCE8: realloc (vg_replace_malloc.c:834)
==480685==    by 0x11F32F97: ResizeMagickMemory (memory.c:1405)
==480685==    by 0x11FD7E80: ConcatenateStringInfo (string.c:538)
==480685==    by 0xB3EEA6F6: UnknownInlinedFun (jpeg.c:2130)
==480685==    by 0xB3EEA6F6: WriteJPEGImage_ (jpeg.c:2813)
==480685==    by 0xB3EEBC98: WriteJPEGImage (jpeg.c:3032)
==480685==    by 0x11E99C1E: WriteImage (constitute.c:1286)
==480685==    by 0x11E68923: ImageToBlob (blob.c:2075)
==480685==    by 0x11C68471: zim_Imagick_getImagesBlob (in /usr/lib64/php/modules/imagick.so)
==480685==    by 0x55F6AC: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1730)
==480685==    by 0x55F6AC: execute_ex (zend_vm_execute.h:53901)
==480685==    by 0x56191A: zend_execute (zend_vm_execute.h:57993)
==480685==    by 0x4D845B: zend_execute_scripts (zend.c:1679)
==480685==    by 0x47571F: php_execute_script (main.c:2650)
==480685== 

```

**Comment by remicollet** [comment] 2021-06-23 15:13
@it-can Can you please give a try to one of the test build

* ImageMagick6-**6.9.12.16-2**.el8.remi
* ImageMagick7-**7.1.0.1-2**.el8.remi
*
which are available in the[ temp directory](https://rpms.remirepo.net/temp/)

**Comment by remicollet** [comment] 2021-06-23 15:22
For memory, RPM fixed by

* https://git.remirepo.net/cgit/rpms/ImageMagick6.git/commit/?id=cf1fe40643ae7a7a22316b18c4db5ab5448dac08
* https://git.remirepo.net/cgit/rpms/ImageMagick7.git/commit/?id=45a6a0dc07d57107f7b8de1cdc2c8c45072eeec4

**Comment by it-can** [comment] 2021-06-23 16:35
Yes this works @remicollet !

**Comment by it-can** [comment] 2021-06-23 16:40
Thanks for the quick work and fixes!

**Comment by remicollet** [comment] 2021-06-23 18:16
> Is it advisable to run imagemagick7 instead of 6?

API are a bit different
With im6 various API are deprecated, and removed in im7
Im7 are some other API

So need to test if your app is ready for 7

**Comment by remicollet** [comment] 2021-06-23 18:18
Here is a diff of reflection (php --re imagick) with both version

https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-imagick.git/commit/?id=de1ca7c3575d108b1aba6f5c67f00cc4e6f20415

**Comment by it-can** [comment] 2021-06-23 19:29
Are you releasing a new version? Or when the upstream fix has been merged?

**Comment by remicollet** [comment] 2021-06-24 05:26
> Are you releasing a new version? Or when the upstream fix has been merged?

I will have prefer to have some feedback from upstream, but as this issue seems critical, and the fix quite trivial, I have run a new set of builds, which are now available in the repository

I also choose to add a REFLECTION file in the php-pecl-imagick-im6/7 package for developers

These files are also tracked on git

- [REFLECTION-im6](https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-imagick.git/plain/REFLECTION-im6)
- [REFLECTION-im7](https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-imagick.git/plain/REFLECTION-im7)

**Comment by remicollet** [comment] 2021-06-25 07:49
For memory both PRs have been merged upstream.

**Closed** 2021-06-25 07:49 UTC
Labels: Feedback expected, Fixed, Upstream bug
