### ISSUE TITLE
php71-php-fpm.service reload reports OK but service fails

### ISSUE THREAD

**Issue by prupert** [remicollet/remirepo#96] opened 2018-02-08 15:09 UTC
A `systemctl reload php71-php-fpm.service` exited successfully when the reload results in a failed state due to a pool socket being unwritable. 

Of course this is a configuration error where one would expect the `systemctl reload` to return an error exit code.

Excerpt from the php-fpm error.log:

```
[06-Feb-2018 22:15:30] NOTICE: Reloading in progress ...
[06-Feb-2018 22:15:30] NOTICE: reloading: execvp("/opt/remi/php71/root/usr/sbin/php-fpm", {"/opt/remi/php71/root/usr/sbin/php-fpm", "--nodaemonize"})
[06-Feb-2018 22:15:31] NOTICE: using inherited socket fd=7, "/var/opt/remi/php71/run/php-fpm/www.sock"
[06-Feb-2018 22:15:31] NOTICE: using inherited socket fd=7, "/var/opt/remi/php71/run/php-fpm/www.sock"
[06-Feb-2018 22:15:31] ERROR: An another FPM instance seems to already listen on <redacted-path>.sock
[06-Feb-2018 22:15:31] ERROR: An another FPM instance seems to already listen on <redacted-path>.sock
[06-Feb-2018 22:15:31] ERROR: FPM initialization failed
[06-Feb-2018 22:15:31] ERROR: FPM initialization failed
```

**Comment by remicollet** [comment] 2018-02-08 16:02
Hmm... of course cannot reproduce...

```
[08-Feb-2018 17:00:43] NOTICE: Reloading in progress ...
[08-Feb-2018 17:00:43] NOTICE: reloading: execvp("/opt/remi/php71/root/usr/sbin/php-fpm", {"/opt/remi/php71/root/usr/sbin/php-fpm", "--nodaemonize"})
[08-Feb-2018 17:00:43] NOTICE: using inherited socket fd=7, "/var/opt/remi/php71/run/php-fpm/www.sock"
[08-Feb-2018 17:00:43] NOTICE: using inherited socket fd=7, "/var/opt/remi/php71/run/php-fpm/www.sock"
[08-Feb-2018 17:00:43] NOTICE: fpm is running, pid 1545
[08-Feb-2018 17:00:43] NOTICE: ready to handle connections
[08-Feb-2018 17:00:43] NOTICE: systemd monitor interval set to 10000ms

```

**Comment by prupert** [comment] 2018-02-08 19:56
Allow me to clarify. My report concerns that reloading `php71-php-fpm.service` reported a success code, but did actually fail. Unless I am misunderstanding the situation, this may be a bug in the `systemd` unit file or the reload procedure in `php-fpm`. 

The misconfiguration of php-fpm was intentionally caused by myself. I would expect `systemctl reload php71-php-fpm.service` to report a fault code when there is a misconfiguration.

**Comment by remicollet** [comment] 2018-02-09 05:52
OK, I understand.

As explain in systemd manual (systemd.service, about ExecReloadà


> Note however that reloading a daemon by sending a signal (as with the example line above) is usually not a good choice, because this is an asynchronous operation
> and hence not suitable to order reloads of multiple services against each other. It is strongly recommended to set ExecReload= to a command that not only triggers a
> configuration reload of the daemon, but also synchronously waits for it to complete.

So system on raise the signal, and return success, and have now way to know about the operation itself.

This create some other issues, ex [bug #1539786](https://bugzilla.redhat.com/show_bug.cgi?id=1539786)

I'm working on a way to improve this, and after some discussion with systemd author, this will imply some important change in php itself.

So can't fix for now.

**Comment by prupert** [comment] 2018-02-09 10:40
Thanks. Is there something I can do to help? 

And would you know where to track progress on the upstream bug?

**Comment by remicollet** [comment] 2018-02-09 11:04
> And would you know where to track progress on the upstream bug?

Best way would be to open an bug on https://bugs.php.net/
So I can close this issue which is not related to the provided packages.

**Comment by prupert** [comment] 2018-02-12 10:14
I have filed a report at https://bugs.php.net/bug.php?id=75953

**Comment by remicollet** [comment] 2018-02-12 10:17
Thanks, so clsing this one.

**Closed by remicollet** 2018-02-12 10:17 UTC
Labels: Upstream bug
