### ISSUE TITLE
Bug in runkit_function_rename

### ISSUE THREAD

**Issue by lifeboatpres** [remicollet/remirepo#21] opened 2015-07-18 00:05 UTC
I installed php56-php-pecl-runkit.x86_64 from the remi repository and it is has a bug. If I use the command runkit_function_rename to rename an internal function it will rename the function but often (not always) then give me an error when I try to create a new function with the same name. I don't have this problem with the runkit_function_redefine command.

Here is a sample program:
```
<?php

ini_set("runkit.internal_override", 1);
runkit_function_rename("json_decode", "php::json_decode");
if (!(function_exists("json_decode")))
 {
 function json_decode()
 {
  echo "Hello\n";
 }
}
print json_decode();
?>
```
Here's the error: PHP Fatal error:  Call to undefined function json_decode() in /u/home/lifeboat/test2.php on line 12

If I change the code so it doesn't check if the function exists before defining it, I get the error: PHP Fatal error:  Cannot redeclare json_decode() in /u/home/lifeboat/test2.php on line 8

Here is the code that generates that error:
```
<?php

ini_set("runkit.internal_override", 1);
runkit_function_rename("json_decode", "php::json_decode");
 function json_decode()
 {
  echo "Hello\n";
 }
print json_decode();
?>
```

**Comment by remicollet** [comment] 2015-07-18 04:33
Please report this to upstream first.

Notice: this extension is mostly dead.

**Comment by remicollet** [comment] 2015-07-18 05:03
You must redefine the function using runkit_function_add

    <?php
    runkit_function_rename("json_decode", "php_json_decode");
    runkit_function_add("json_decode", "", 'echo "Hello\n";');
    print json_decode();

And

    $ php56 -d runkit.internal_override=1 /tmp/foo.php
    Hello

**Comment by remicollet** [comment] 2015-07-18 05:03
Closing as not a bug.

**Closed by remicollet** 2015-07-18 05:03 UTC
