### ISSUE TITLE
php7.0-7.4: wkhtmlto breaks Imagick::getImageHeight for JPG

### ISSUE THREAD

**Issue by bjo81** [remicollet/remirepo#207] opened 2022-06-08 07:13 UTC
On a box running Oracle Linux 8.6:

As already discussed yesterday on IRC, wkhtmlto breaks Imagick::getImageHeight for JPG files - the returned value is always 0.

**Comment by remicollet** [comment] 2022-06-08 07:20
Sorry, cannot reproduced

**Comment by bjo81** [comment] 2022-06-08 07:45
I tried it now on a fresh AlmaLinux 8.6 from docker.io/library/almalinux

- Installed php70-php-pecl-imagick-im6 and php70-php-cli
- Ran `php70 test.php` which contained
````
$image=new Imagick("test.jpg");
$height=$image->getImageHeight();
print "the image height is ".$height;
```
- got some value
- installed php70-php-wkhtmltox
- ran `php70 test.php` and got 0 as height

Which OS did you try to reproduce?

**Comment by remicollet** [comment] 2022-06-08 08:00
> Which OS did you try to reproduce?

All package are build on RHEL 8.6
Test run on CentOS 8 Stream

```
# php70 /tmp/foo.php 
Using PHP 7.0.33
/tmp/test.jpg is 864 x 1152
# php71 /tmp/foo.php 
Using PHP 7.1.33
/tmp/test.jpg is 864 x 1152
# php72 /tmp/foo.php 
Using PHP 7.2.34
/tmp/test.jpg is 864 x 1152
# php73 /tmp/foo.php 
Using PHP 7.3.33
/tmp/test.jpg is 864 x 1152
# php74 /tmp/foo.php 
Using PHP 7.4.30
/tmp/test.jpg is 864 x 1152

```

In all cases, with **wkhtmltox** and **magick** extensions enabled

**Comment by remicollet** [comment] 2022-06-09 14:13
Ok, was able to reproduce

**imagick** alone works:

```
# php72 -n -d extension=imagick /tmp/foo.php 
Using PHP 7.2.34
/tmp/test.jpg is 864 x 1152
```

doesn't work with **wkhtmltox**

```
# php72 -n -d extension=imagick -d extension=wkhtmltox -d extension=gd /tmp/foo.php 
Using PHP 7.2.34
/tmp/test.jpg is 0 x 0

```

But works with **gd**

```
# php72 -n -d extension=gd -d extension=imagick -d extension=wkhtmltox  /tmp/foo.php 
Using PHP 7.2.34
/tmp/test.jpg is 864 x 1152

```

So the workaround is to install the gd extension.

**Comment by remicollet** [comment] 2022-06-15 15:29
No news, so closing.

**Closed by remicollet** 2022-06-15 15:29 UTC
Labels: Feedback expected, PHP stack dependency, Won't fix, Workaround
