### ISSUE TITLE
php-oci8 fails to install with oracle-database-free-23c-1.0-1.x86_64

### ISSUE THREAD

**Issue by jbweb** [remicollet/remirepo#269] opened 2024-09-07 08:21 UTC
Hi

I'm trying to install php-oci8 in combination with the oracle-database-free-23c-1.0-1.x86_64 package from Oracle.
```
# dnf install php-oci8
Last metadata expiration check: 0:21:31 ago on 2024-09-07T09:58:53 CEST.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libclntsh.so.23.1()(64bit) needed by php-oci8-8.2.23-1.el9.remi.x86_64 from remi-modular
```

oracle-database-free-23c-1.0-1.x86_64 should provide this:

```
# dnf provides libclntsh.so
Last metadata expiration check: 0:10:30 ago on 2024-09-07T09:58:53 CEST.
oracle-database-free-23c-1.0-1.x86_64 : Oracle 23c Free Database
Repo        : @System
Matched from:
Provide    : libclntsh.so = 23.1
```

oracle-database-free-23c-1.0-1.x86_64 is install from a RPM with dnf

`# dnf localinstall -y oracle-database-free-23c-1.0–1.el8.x86_64.rpm`

Trying to install oracle-instantclient-basic (which I would normally do on a non-Oracle-database server), results in conflicts, which is to expected.

```
# dnf localinstall oracle-instantclient-basic-23.5.0.24.07-1.el9.x86_64.rpm
Last metadata expiration check: 0:18:15 ago on 2024-09-07T09:58:53 CEST.
Error: 
 Problem: package oracle-instantclient-basic-23.5.0.24.07-1.el9.x86_64 from @commandline conflicts with genezi <= 23.5 provided by oracle-database-free-23c-1.0-1.x86_64 from @System
  - package oracle-instantclient-basic-23.5.0.24.07-1.el9.x86_64 from @commandline conflicts with libclntsh.so <= 23.5
[...]
```

Is there anyway it could be possible to make php-oci8 compatible with oracle-database-free-23c-1.0-1.x86_64? Or I'm going about this the wrong way?

**Comment by remicollet** [comment] 2024-09-08 05:11
This means **oracle-database-free-23c** is badly packaged by Oracle and doesn't provide what it should.

Try to report this issue to Oracle ;)

Sorry, but I don't see a proper solution to this

Older way (no requires of `libclntsh.so.23.1()(64bit)`) raise issue allowing non working installation, and breaking installation on update.

@cjbj any idea out to report this ?

**Comment by remicollet** [comment] 2024-09-08 07:09
For now it seems better to not install PHP on the same server than Oracle Database

If you really need it, run php-fpm in a container.

**Comment by cjbj** [comment] 2024-09-08 07:18
DB and Instant Client rpms cannot be  installed concurrently. This is by design.

**Comment by remicollet** [comment] 2024-09-08 08:05
> DB and Instant Client rpms cannot be installed concurrently. This is by design. 

Yes, this makes sense.

But if the database provides the client library, the RPM should provides it (`libclntsh.so.23.1()(64bit)`), like the RPM of the client does.

**Comment by remicollet** [comment] 2024-09-11 08:35
Closing as nothing I can fixed on my side.
Sorry.

**Closed by remicollet** 2024-09-11 08:35 UTC
Labels: PHP stack dependency, Assistance
