### ISSUE TITLE
Dependencies failed (libavif.so.14)

### ISSUE THREAD

**Issue by cmahlig** [remicollet/remirepo#219] opened 2022-08-10 11:39 UTC
Hi !

We have a problem under ol8 :
```
~$ dnf update
Last metadata expiration check: 0:22:36 ago on Wed 10 Aug 2022 11:47:49 AM CEST.
Error: 
 Problem: cannot install the best update candidate for package gd3php-2.3.3-4.el8.remi.x86_64
  - nothing provides libavif.so.14()(64bit) needed by gd3php-2.3.3-8.el8.remi.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
Can you reproduce it ?

**Comment by remicollet** [comment] 2022-08-10 12:45
is EPEL enabled ?
It is mandatory

For memory, for a proper installation follow the [Wizard instructions](https://rpms.remirepo.net/wizard/)

**Comment by remicollet** [comment] 2022-08-10 12:46
Notice: OL8 it a terrible choice, they provide a specific fake epel repository which is not EPEL, so use the real EPEL instead of the fake one.

**Comment by remicollet** [comment] 2022-08-10 15:07
Duplicate of #216

**Closed by remicollet** 2022-08-10 15:07 UTC
Labels: Assistance
